### ISSUE TITLE
Selected commands from extensions does not properly save.

### ISSUE THREAD

**Issue by maxiy01** [Josh-XT/AGiXT#1256] opened 2024-09-24 21:39 UTC
### Description

I'm not sure what exactly to write about issue, so here ishow to reproduce:
Agent Management -> Modify Agent ->Select extensions -> select commands -> click save -> refresh page -> some commands are not selected

Selecting commands:
![1 (2)](https://github.com/user-attachments/assets/7d2866dc-ca2f-4534-899f-6c88f64e15d7)
![2 (2)](https://github.com/user-attachments/assets/08797754-ecab-49af-97ff-1daa218e5bfa)
![3](https://github.com/user-attachments/assets/9b535c7e-f6f7-47ea-8a64-7111a615a061)
Enabling memory training and clicking save button:
![4 (2)](https://github.com/user-attachments/assets/18992808-3ccd-4a12-9274-6993aaa846d7)

Upon refresh:
![11 (2)](https://github.com/user-attachments/assets/7c1c6447-93b4-4efa-a308-0190b0960651)
![22](https://github.com/user-attachments/assets/0006dc25-5484-4640-a8d6-531315208c2b)
![33](https://github.com/user-attachments/assets/adeefd06-0420-450a-9530-797ffc6724d3)
![44](https://github.com/user-attachments/assets/3d4d9e58-840f-490b-9df8-5692b89bf4d2)

### Operating System

- [ ] Linux
- [X] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by birdup000** [comment] 2024-10-13 20:53
Hi thank you for reporting this, looking into this issue I have noticed it too! Hopefully I'll have a fix out for this soon, the issue is due to chain commands not properly being registered as a regular command.

**Comment by birdup000** [comment] 2024-10-19 21:03
There was a recent commit  e04a69deb986cb41827b57c23d8cc4a9867b8cbc that fixed the saving for the chain commands and they are now in a different category called AGiXT Chains.

**Comment by Josh-XT** [comment] 2024-10-20 02:05
This should be resolved in v1.6.16.

**Closed by Josh-XT** 2024-10-20 02:05 UTC
Labels: type | report | bug, needs triage
